### ISSUE TITLE
No requests happen when selecting image

### ISSUE THREAD

**Issue by IvanCeban** [rpldy/drive-uploady#1]
Hi Yoav, 
'drive-uploady' is exactly what I need on my current project. Thank you for this plugin!
Unfortunately when I click the UploadButton, choose an image and click 'open', nothing happens. No requests are sent to Google Drive.
I've installed the following dependencies:
**@rpldy/uploader
@rpldy/uploady
@rpldy/upload-button
drive-uploady**

Here is an attached screenshot of my component where I use 'drive-uploady'

I bet I'm doing something wrong. But what? Can you help, please?

![Screenshot 2021-02-12 121610](https://user-images.githubusercontent.com/13540144/107757129-cd48fa80-6d2d-11eb-846a-2d57c970ed68.png)
![Screenshot 2021-02-12 122617](https://user-images.githubusercontent.com/13540144/107757152-d3d77200-6d2d-11eb-9a4e-23b06430d44e.png)

**Comment by yoavniran** [comment]
hey @IvanCeban 
I will check whats going on and let you know.

**Comment by yoavniran** [comment]
@IvanCeban 
I just upgraded the uploady dependencies and tried uploading to Drive and it worked.
Are there any errors in the browser dev console?
Did you make sure to allow the URL youre testing from the google api console?
Also, Im pretty sure, when you set a parent param, it should an ID and not the name of the folder ("Share"). try without it and see if that makes a difference

**Comment by IvanCeban** [comment]
Hi @yoavniran,
thank you for your quick reply!

There are no errors in dev console (see the attached gif)

I'm working on localhost and it was added to the authorized URIs in google API console. (see attached screenshot)

I've tried even without parameters. Expecting that in this case images will be uploaded in the root directory. But still with no success.

![Screenshot 2021-02-18 111916](https://user-images.githubusercontent.com/13540144/108335113-4d160f80-71db-11eb-8699-2646bf8d7553.png)

![DriveUploadyExample](https://user-images.githubusercontent.com/13540144/108334925-12ac7280-71db-11eb-9b77-3b6f53fc0d55.gif)

**Comment by yoavniran** [comment]
Hey @IvanCeban 
sorry for not getting back to you sooner. been very busy couple of weeks
Unfortunately, I cant really tell whats the issue from the info you provided. 

On the face of it , it looks all ok.
What id suggest is for you to debug the code a little, put breakpoints in the `getDriveEnhancer.js` and `getDriveSender.js` files in the devtools. See how far it goes and where it breaks. 
As I cant reproduce your problem Im unable to assist further than that

Once you see where it is that the code is failing please let me know and I will try to fix if its an issue in the lib's code

**Comment by IvanCeban** [comment]
Hi @yoavniran 
thank you for your reply, unfortunately I was limited in time and as I couldn't make the drive-uploady work on my project, I had to implement a workaround. So I'm closing this issue.
Thank you for your plugin and hope to use it next time
