### ISSUE TITLE
Files previewing but not uploading to drive

### ISSUE THREAD

**Issue by Hassaan-Baig** [rpldy/drive-uploady#2]

**Comment by Hassaan-Baig** [comment]
The file that I upload is shown in preview but does not get uploaded to google drive

**Comment by yoavniran** [comment]
Hey @Hassaan-Baig , Im going to need a lot more info to be able to understand what issue you're facing. please share code, preferably a code sandbox.
What do you see in the network tab?

**Comment by Hassaan-Baig** [comment]
<img width="519" alt="Screenshot 2022-10-24 at 4 27 37 PM" src="https://user-images.githubusercontent.com/68878411/197515871-a796244d-9e95-4ae1-ae04-db89c5c34570.png">

here is the code snippet I am using.
I have added my clientID and folder id that I want the files to be uploaded.

This is the error that I am getting in my console.

<img width="946" alt="Screenshot 2022-10-24 at 4 32 35 PM" src="https://user-images.githubusercontent.com/68878411/197516414-53a15c3d-5362-4260-a070-379cf4f382ec.png">

**Comment by Hassaan-Baig** [comment]
https://codesandbox.io/s/nhswn

this is the code sandbox that I am using.

**Comment by yoavniran** [comment]
@Hassaan-Baig looks like I need to update the SDK used by this library.
I will look into this and let you know
thanks for reporting

**Comment by Hassaan-Baig** [comment]
thanks for looking into it.

**Comment by yoavniran** [comment]
@Hassaan-Baig 
just published v0.3.0 that uses the new google oauth library and flow
Please upgrade and make sure to read the [authentication readme section](https://github.com/rpldy/drive-uploady#authentication).
Hopefully that should fix any issues that existed before.
Notice that you need to set up your app correctly in the Google API Console for the upload to be successful.

**Comment by Hassaan-Baig** [comment]
Thankyou so much. I will definitely try this.
